In [1]:
import numpy as np

#Array Operations

Arithmetic operations

In [3]:
a1= np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])

In [4]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1-a2

array([-5, -5, -5, -5, -5])

In [6]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [19]:
a1**a2



array([      1,     128,    6561,  262144, 9765625])

In [21]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Boardcasting

In [10]:
l = [10,20,30]
arr=np.array(l)

In [12]:
arr+10

array([20, 30, 40])

In [15]:
arr2=np.arange(1,26).reshape(5,5)
        

In [16]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow copy

In [40]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
slice = a[:5]
slice = slice*10
slice  #extra space

array([10, 20, 30, 40, 50])

In [42]:
a   #no changes

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
a[4:6]*10 # no changes

array([50, 60])

In [44]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
# b = a #changes

In [36]:
# b[0]=99

In [37]:
# b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
# a #changes

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
#if 

In [45]:
b = a.copy() #no changes

In [46]:
b[0]=99

In [47]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operations

In [50]:
A= np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [51]:
A

array([[1, 2],
       [3, 4]])

In [52]:
B

array([[5, 6],
       [7, 8]])

In [53]:
A@B

array([[19, 22],
       [43, 50]])

In [54]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [55]:
A.T

array([[1, 3],
       [2, 4]])

Advance Array Manipulation

stacking Array

In [56]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [57]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

 Spliting array

In [60]:
c=np.arange(16).reshape(4,4)

In [61]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [63]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]