In [1]:
import numpy as np

Basic array creation

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3,4,5.4,]

In [4]:
a

[1, 2, 3, 4, 5.4]

In [5]:
np.array(a)

array([1. , 2. , 3. , 4. , 5.4])

In [6]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

In [9]:
arr= np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [10]:
arr=np.zeros((6,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr=np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Random Generation function 

In [13]:
arr=np.random.rand(10)
arr #noramlization

array([0.13873989, 0.62379181, 0.48581176, 0.34148263, 0.96796743,
       0.0066852 , 0.4941599 , 0.27186933, 0.85814684, 0.21048745])

In [14]:
arr=np.random.randn(10)
arr #SD

array([ 0.93227748, -0.60050557, -0.41126717,  1.06423687,  0.07653649,
        1.23257236,  1.34396062, -1.0888789 ,  1.82116002,  1.75369924])

In [15]:
arr=np.random.randint(10,20,10)
arr

array([18, 16, 12, 13, 18, 11, 10, 12, 17, 10])

Array Attributes

In [16]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.shape

(3, 3)

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr.size

9

Array Methods

In [20]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.max()

9

In [22]:
arr.min()

1

In [23]:
arr.sum()

45

In [24]:
np.sum(arr,0) #column

array([12, 15, 18])

In [25]:
np.sum(arr,1) #row

array([ 6, 15, 24])

In [26]:
arr.mean()

5.0

In [27]:
arr.std()

2.581988897471611

In [28]:
arr.argmax() #max value index like = 9 and index =8

8

In [29]:
arr.argmin() #min value index like = 1 and index =0

0

Resize and Reshape

In [30]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [31]:
arr.reshape(6,5) #reshape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
arr= arr.reshape(6,5) #resize

In [33]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])