Numpy Indexing & Slicing " Vectors "

In [2]:
import numpy as np

In [3]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[5] #indexing

np.int64(16)

In [5]:
arr[1:5] #slicing

array([12, 13, 14, 15])

In [6]:
arr[3::2]

array([14, 16, 18, 20])

Numpy Indexing & Slicing " Matrix "

In [7]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[3,2] #3=row & 2=column/index

np.int64(18)

arr[2,3]

In [18]:
slice=arr[2:4,2:4]

In [19]:
slice

array([[13, 14],
       [18, 19]])

In [20]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [23]:
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

In [24]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

Boolean indexing

In [26]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
bool_index=arr%2==0 #condition of even no.
bool_index #o/p= True or False

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [28]:
arr=arr[bool_index] #arr[index=bool_index]
arr #even no.

array([12, 14, 16, 18, 20])